version: '3'

services:
  db:
    image: mysql:5.7
    container_name: test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    expose:
      - 3306

  app:
    build: ./dockerfiles/test_app
    container_name: test_app
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./src:/go/src/app
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_HOSTNAME: "db"
      DB_PORT: "3306"
      DB_DATABASE: "test_db"
