version: '3'

services:
  db:
    image: mysql:8.0.4
    container_name: test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    expose:
      - 3306

  app:
    image: golang:onbuild
    container_name: test_app
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./src:/go/src/app
    environment:
      DEBUG_FLAG: "true"
      DB_PASSWD: "password"
