version: '3'

services:
  app:
    image: golang:onbuild
    container_name: test_app
    links:
      - db
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./src:/go/src/app
    environment:
      DEBUG_FLAG: "true"
      DB_PASSWD: "password"

  db:
    image: mysql:8.0.4
    container_name: test_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-vol:/data
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  my-vol:
